#ifndef CONST_VARIABLE_HPP
#define CONST_VARIABLE_HPP

enum {
	USERNAME_LEN = 21,
	PASSWORD_LEN = 31,
	NAME_LEN = 16,
	MAIL_ADDR_LEN = 31,
	TRAIN_ID_LEN = 21,
	STATION_LEN = 31,
	STATION_NUM_MAX = 101,
	DATE_MAX = 93,
	STATUS_SUCCESS = 1,
	STATUS_PENDING = 2,
	STATUS_REFUNDED = 3,
};

#endif // CONST_VARIABLE_HPP
